# Generated by Django 3.2.4 on 2021-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('codigo', models.TextField()),
                ('valor', models.FloatField()),
                ('valor_repasse', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
