# Generated by Django 3.2.4 on 2021-08-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0002_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='valor_repasse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
