# Generated by Django 3.2.4 on 2021-08-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0003_alter_exame_valor_repasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.TextField()),
                ('cpf', models.TextField()),
                ('nome_mae', models.TextField()),
                ('data_nascimento', models.DateTimeField()),
                ('data_exame', models.DateTimeField()),
                ('exame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unimagem.exame')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unimagem.medico')),
            ],
        ),
    ]
