# Generated by Django 3.2.4 on 2021-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0004_examerealizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examerealizado',
            name='data_nascimento',
            field=models.TextField(),
        ),
    ]
