# Generated by Django 3.2.4 on 2021-08-13 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unimagem', '0005_alter_examerealizado_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='examerealizado',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
