# Generated by Django 3.2.4 on 2021-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0007_caixa_recebimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examerealizado',
            name='exame',
        ),
        migrations.AddField(
            model_name='examerealizado',
            name='exame',
            field=models.ManyToManyField(blank=True, null=True, to='unimagem.Exame'),
        ),
    ]
