# Generated by Django 3.2.4 on 2021-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0008_auto_20210813_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examerealizado',
            name='exame',
            field=models.ManyToManyField(to='unimagem.Exame'),
        ),
    ]
