# Generated by Django 3.2.4 on 2021-08-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0009_alter_examerealizado_exame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examerealizado',
            name='exame',
        ),
        migrations.AddField(
            model_name='examerealizado',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unimagem.exame'),
        ),
    ]
