# Generated by Django 3.2.4 on 2021-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0011_auto_20210813_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimento',
            name='tipo',
            field=models.TextField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão Débito', 'Cartão Débito'), ('Cartão Crédito', 'Cartão Crédito'), ('PIX', 'PIX'), ('Transferência Bancaria', 'Transferência Bancaria'), ('Cheque', 'Cheque')]),
        ),
    ]
