# Generated by Django 3.2.4 on 2021-08-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0014_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='recebimento',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='atendimento',
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimagem.examerealizado')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimagem.recebimento')),
            ],
        ),
        migrations.AddField(
            model_name='caixa',
            name='atendimento',
            field=models.ManyToManyField(to='unimagem.Lancamento'),
        ),
    ]
