# Generated by Django 3.2.4 on 2021-08-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0015_auto_20210815_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='aberto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
