# Generated by Django 3.2.4 on 2021-08-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0016_caixa_aberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='hora_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_fechamento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
