# Generated by Django 3.2.4 on 2021-08-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimagem', '0017_auto_20210815_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unimagem.recebimento'),
        ),
    ]
