# Generated by Django 3.2.4 on 2021-07-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.TextField()),
                ('logradouro', models.TextField()),
                ('numero', models.TextField()),
                ('complemento', models.TextField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('uf', models.TextField()),
                ('pais', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TagProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('valor', models.FloatField()),
                ('descricao', models.TextField()),
                ('imagens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imagem')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tagproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('dono', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.endereco')),
                ('estoque', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estoque')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.imagem')),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
    ]
