# Generated by Django 3.2.4 on 2021-07-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='produto',
        ),
        migrations.CreateModel(
            name='EstoqueAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ManyToManyField(to='app.EstoqueAtivo'),
        ),
    ]
