# Generated by Django 3.2.4 on 2021-07-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210705_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='estoque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estoque'),
        ),
    ]
